"""Script to generate a massive, authentic database of 130+ Central and State welfare schemes."""

import json
import os

SCHEMES = [
    # ==========================================
    # CENTRAL GOVERNMENT: AGRICULTURE & FARMERS
    # ==========================================
    {
        "id": "SCH_001",
        "name": "PM-Kisan Samman Nidhi (PM-KISAN)",
        "issuing_body": "Ministry of Agriculture and Farmers Welfare",
        "state": None,
        "category": "Agriculture",
        "description": "Direct income support of ₹6,000 per year in three equal installments of ₹2,000 directly to bank accounts of landholding farmer families across India.",
        "eligibility_rules": {"max_land_size_hectares": 2.0, "is_farmer": True},
        "source_url": "https://pmkisan.gov.in",
    },
    {
        "id": "SCH_002",
        "name": "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
        "issuing_body": "Ministry of Agriculture and Farmers Welfare",
        "state": None,
        "category": "Agriculture",
        "description": "Comprehensive crop insurance coverage against non-preventable natural risks, crop loss, floods, drought, and post-harvest damage at lowest premium rates (1.5% to 2% for farmers).",
        "eligibility_rules": {"is_farmer": True},
        "source_url": "https://pmfby.gov.in",
    },
    {
        "id": "SCH_003",
        "name": "Kisan Credit Card (KCC) Scheme",
        "issuing_body": "Ministry of Agriculture and Farmers Welfare",
        "state": None,
        "category": "Agriculture",
        "description": "Concessional institutional credit up to ₹3,00,000 at 4% effective interest rate for agricultural cultivation, dairy farming, animal husbandry, and fisheries working capital.",
        "eligibility_rules": {"min_age": 18, "max_age": 75, "is_farmer": True},
        "source_url": "https://agricoop.nic.in",
    },
    {
        "id": "SCH_004",
        "name": "Pradhan Mantri Krishi Sinchayee Yojana (PMKSY - Micro Irrigation)",
        "issuing_body": "Ministry of Agriculture and Farmers Welfare",
        "state": None,
        "category": "Agriculture",
        "description": "Financial subsidy of up to 55% for small/marginal farmers and 45% for other farmers for installing drip and sprinkler micro-irrigation systems under Per Drop More Crop.",
        "eligibility_rules": {"is_farmer": True},
        "source_url": "https://pmksy.gov.in",
    },
    {
        "id": "SCH_005",
        "name": "Sub-Mission on Agricultural Mechanization (SMAM - Tractor & Farm Machinery Subsidy)",
        "issuing_body": "Ministry of Agriculture and Farmers Welfare",
        "state": None,
        "category": "Agriculture",
        "description": "Subsidy ranging from 40% to 50% for farmers and Custom Hiring Centers (CHCs) to purchase modern agricultural machinery including tractors, power tillers, and harvesters.",
        "eligibility_rules": {"min_age": 18, "is_farmer": True},
        "source_url": "https://agrimachinery.nic.in",
    },
    {
        "id": "SCH_006",
        "name": "PM Kisan Maan Dhan Yojana (PM-KMY - Farmer Pension)",
        "issuing_body": "Ministry of Agriculture and Farmers Welfare",
        "state": None,
        "category": "Agriculture",
        "description": "Old age social security scheme offering assured monthly pension of ₹3,000 after attaining 60 years of age for small and marginal farmers.",
        "eligibility_rules": {"min_age": 18, "max_age": 40, "max_land_size_hectares": 2.0, "is_farmer": True},
        "source_url": "https://maandhan.in",
    },
    {
        "id": "SCH_007",
        "name": "Paramparagat Krishi Vikas Yojana (PKVY - Organic Farming)",
        "issuing_body": "Ministry of Agriculture and Farmers Welfare",
        "state": None,
        "category": "Agriculture",
        "description": "Financial assistance of ₹50,000 per hectare over 3 years for cluster organic farming, soil health management, organic certification, and value addition.",
        "eligibility_rules": {"is_farmer": True},
        "source_url": "https://pgsindia-ncof.gov.in",
    },
    {
        "id": "SCH_008",
        "name": "Agriculture Infrastructure Fund (AIF)",
        "issuing_body": "Ministry of Agriculture and Farmers Welfare",
        "state": None,
        "category": "Agriculture",
        "description": "Medium-long term debt financing with 3% per annum interest subvention and credit guarantee up to ₹2 Crores for post-harvest management infrastructure and community farming assets.",
        "eligibility_rules": {"min_age": 18},
        "source_url": "https://agriinfra.dac.gov.in",
    },
    {
        "id": "SCH_009",
        "name": "Pradhan Mantri Matsya Sampada Yojana (PMMSY - Fisheries)",
        "issuing_body": "Ministry of Fisheries, Animal Husbandry and Dairying",
        "state": None,
        "category": "Agriculture",
        "description": "Financial assistance of 40% (general) and 60% (women, SC, ST) for establishing aquaculture ponds, fish feed mills, biofloc units, hatcheries, and refrigerated transport.",
        "eligibility_rules": {"min_age": 18},
        "source_url": "https://pmmsy.dof.gov.in",
    },
    {
        "id": "SCH_010",
        "name": "Rashtriya Gokul Mission & Dairy Subsidy",
        "issuing_body": "Ministry of Fisheries, Animal Husbandry and Dairying",
        "state": None,
        "category": "Agriculture",
        "description": "Subsidies up to 50% (maximum ₹50 Lakh) for establishing high-yielding breed multiplication dairy farms, semen stations, and modern cattle housing.",
        "eligibility_rules": {"min_age": 18},
        "source_url": "https://dahd.nic.in",
    },

    # ==========================================
    # CENTRAL GOVERNMENT: MSME, BUSINESS & SKILLS
    # ==========================================
    {
        "id": "SCH_011",
        "name": "Pradhan Mantri Mudra Yojana - Shishu Loan",
        "issuing_body": "Ministry of Finance",
        "state": None,
        "category": "MSME & Business",
        "description": "Collateral-free institutional business loans up to ₹50,000 at low interest rates for starting micro-enterprises, small shops, artisan ventures, and trading units.",
        "eligibility_rules": {"min_age": 18, "max_age": 65},
        "source_url": "https://www.mudra.org.in",
    },
    {
        "id": "SCH_012",
        "name": "Pradhan Mantri Mudra Yojana - Kishore & Tarun Loan",
        "issuing_body": "Ministry of Finance",
        "state": None,
        "category": "MSME & Business",
        "description": "Collateral-free business expansion loans from ₹50,000 to ₹10,00,000 for established small businesses, manufacturers, service providers, and vendors.",
        "eligibility_rules": {"min_age": 18, "max_age": 65},
        "source_url": "https://www.mudra.org.in",
    },
    {
        "id": "SCH_013",
        "name": "PM Employment Generation Programme (PMEGP)",
        "issuing_body": "Ministry of Micro, Small and Medium Enterprises",
        "state": None,
        "category": "MSME & Business",
        "description": "Credit-linked government subsidy scheme providing 15% to 35% margin money subsidy on bank loans up to ₹50 Lakh for manufacturing and ₹20 Lakh for service units.",
        "eligibility_rules": {"min_age": 18, "min_education": "8th Pass for projects > ₹10L"},
        "source_url": "https://www.kviconline.gov.in/pmegpeportal",
    },
    {
        "id": "SCH_014",
        "name": "PM Vishwakarma Scheme",
        "issuing_body": "Ministry of Micro, Small and Medium Enterprises",
        "state": None,
        "category": "MSME & Business",
        "description": "End-to-end holistic support for traditional artisans and craftspeople including PM Vishwakarma Certificate, 5-7 days basic training with ₹500/day stipend, ₹15,000 toolkit e-voucher, and collateral-free enterprise credit up to ₹3 Lakh at 5% interest.",
        "eligibility_rules": {"min_age": 18, "traditional_artisan": True},
        "source_url": "https://pmvishwakarma.gov.in",
    },
    {
        "id": "SCH_015",
        "name": "PM Street Vendor's AtmaNirbhar Nidhi (PM SVANidhi)",
        "issuing_body": "Ministry of Housing and Urban Affairs",
        "state": None,
        "category": "MSME & Business",
        "description": "Micro-credit facility for urban and semi-urban street vendors offering initial working capital loan of ₹10,000 with 7% interest subsidy, upgrading to ₹20,000 and ₹50,000 on timely repayment.",
        "eligibility_rules": {"min_age": 18, "occupation": "Street Vendor / Hawkers"},
        "source_url": "https://pmsvanidhi.mohua.gov.in",
    },
    {
        "id": "SCH_016",
        "name": "Stand-Up India Scheme",
        "issuing_body": "Ministry of Finance",
        "state": None,
        "category": "MSME & Business",
        "description": "Bank loans between ₹10 Lakh and ₹1 Crore to at least one SC/ST borrower and at least one woman borrower per bank branch for setting up greenfield non-farm enterprise.",
        "eligibility_rules": {"min_age": 18, "target_group": "SC/ST or Women"},
        "source_url": "https://www.standupmitra.in",
    },
    {
        "id": "SCH_017",
        "name": "PM Kaushal Vikas Yojana (PMKVY 4.0)",
        "issuing_body": "Ministry of Skill Development and Entrepreneurship",
        "state": None,
        "category": "Skill Development",
        "description": "Free industry-aligned short-term skill training, RPL certification, and job placement assistance in trending technical and service job roles with assessment fee coverage.",
        "eligibility_rules": {"min_age": 15, "max_age": 45},
        "source_url": "https://www.pmkvyofficial.org",
    },
    {
        "id": "SCH_018",
        "name": "Credit Guarantee Fund Trust for Micro and Small Enterprises (CGTMSE)",
        "issuing_body": "Ministry of Micro, Small and Medium Enterprises",
        "state": None,
        "category": "MSME & Business",
        "description": "Collateral-free credit facility for new and existing Micro and Small Enterprises up to ₹500 Lakh with credit guarantee coverage up to 85%.",
        "eligibility_rules": {"min_age": 18},
        "source_url": "https://www.cgtmse.in",
    },
    {
        "id": "SCH_019",
        "name": "Scheme for Promotion of Innovation, Rural Industry and Entrepreneurship (ASPIRE)",
        "issuing_body": "Ministry of Micro, Small and Medium Enterprises",
        "state": None,
        "category": "MSME & Business",
        "description": "Financial aid up to ₹100 Lakh for setting up Livelihood Business Incubators (LBI) and Technology Business Incubators (TBI) in rural and agro-industry sectors.",
        "eligibility_rules": {"min_age": 18},
        "source_url": "https://aspire.msme.gov.in",
    },
    {
        "id": "SCH_020",
        "name": "National Apprenticeship Promotion Scheme (NAPS)",
        "issuing_body": "Ministry of Skill Development and Entrepreneurship",
        "state": None,
        "category": "Skill Development",
        "description": "Direct financial stipend support of 25% of prescribed stipend up to ₹1,500 per month per apprentice directly to youth undergoing formal industry on-the-job training.",
        "eligibility_rules": {"min_age": 14, "max_age": 35},
        "source_url": "https://www.apprenticeshipindia.gov.in",
    },

    # ==========================================
    # CENTRAL GOVERNMENT: HEALTH & FAMILY WELFARE
    # ==========================================
    {
        "id": "SCH_021",
        "name": "Ayushman Bharat - PM Jan Arogya Yojana (AB-PMJAY)",
        "issuing_body": "National Health Authority, Ministry of Health",
        "state": None,
        "category": "Health",
        "description": "World's largest health assurance scheme providing cashless hospitalisation cover of up to ₹5,00,000 per family per year for secondary and tertiary care across 27,000+ empaneled hospitals.",
        "eligibility_rules": {"income_limit": 300000, "bpl_secc_eligible": True},
        "source_url": "https://pmjay.gov.in",
    },
    {
        "id": "SCH_022",
        "name": "Ayushman Bharat - PMJAY Senior Citizen Universal Cover (70+ Years)",
        "issuing_body": "National Health Authority, Ministry of Health",
        "state": None,
        "category": "Health",
        "description": "Universal cashless healthcare cover of ₹5,00,000 per year for all senior citizens aged 70 years and above, irrespective of their socio-economic status or family income.",
        "eligibility_rules": {"min_age": 70},
        "source_url": "https://pmjay.gov.in",
    },
    {
        "id": "SCH_023",
        "name": "Pradhan Mantri Bharatiya Janaushadhi Pariyojana (PMBJP)",
        "issuing_body": "Department of Pharmaceuticals, Ministry of Chemicals and Fertilizers",
        "state": None,
        "category": "Health",
        "description": "Access to high-quality generic medicines and surgical products at 50% to 90% lesser prices than branded equivalents through 10,000+ dedicated Kendras across India.",
        "eligibility_rules": {},
        "source_url": "http://janaushadhi.gov.in",
    },
    {
        "id": "SCH_024",
        "name": "PM National Dialysis Programme (PMNDP)",
        "issuing_body": "Ministry of Health and Family Welfare",
        "state": None,
        "category": "Health",
        "description": "Free of cost hemodialysis and peritoneal dialysis services at District Hospitals and Sub-District healthcare centers for BPL renal patients.",
        "eligibility_rules": {"income_limit": 250000},
        "source_url": "https://nhm.gov.in",
    },
    {
        "id": "SCH_025",
        "name": "Nikshay Poshan Yojana (TB Nutritional Support)",
        "issuing_body": "Ministry of Health and Family Welfare",
        "state": None,
        "category": "Health",
        "description": "Direct Benefit Transfer (DBT) of ₹1,000 per month directly to the bank account of all diagnosed Tuberculosis (TB) patients for nutritional support throughout treatment duration.",
        "eligibility_rules": {"diagnosed_condition": "Tuberculosis"},
        "source_url": "https://nikshay.in",
    },

    # ==========================================
    # CENTRAL GOVERNMENT: WOMEN & CHILD WELFARE
    # ==========================================
    {
        "id": "SCH_026",
        "name": "Pradhan Mantri Matru Vandana Yojana (PMMVY)",
        "issuing_body": "Ministry of Women and Child Development",
        "state": None,
        "category": "Women & Child",
        "description": "Maternity cash incentive of ₹5,000 in two installments for pregnant women and lactating mothers for first living child, and ₹6,000 for second child if girl child, promoting institutional delivery and child nutrition.",
        "eligibility_rules": {"min_age": 19, "gender": "Female", "is_pregnant_or_lactating": True},
        "source_url": "https://pmmvy.wcd.gov.in",
    },
    {
        "id": "SCH_027",
        "name": "Sukanya Samriddhi Yojana (SSY)",
        "issuing_body": "Ministry of Finance",
        "state": None,
        "category": "Women & Child",
        "description": "High-interest (8.2%+ p.a.) government savings scheme for girl children with complete triple tax exemption (EEE) under Section 80C to secure higher education and marriage funds.",
        "eligibility_rules": {"max_age": 10, "gender": "Female"},
        "source_url": "https://www.indiapost.gov.in",
    },
    {
        "id": "SCH_028",
        "name": "Pradhan Mantri Ujjwala Yojana 2.0 (PMUY)",
        "issuing_body": "Ministry of Petroleum and Natural Gas",
        "state": None,
        "category": "Women & Child",
        "description": "Free LPG gas connection with first cylinder refill and hotplate/stove provided to adult women from poor households with ₹300 per cylinder subsidy.",
        "eligibility_rules": {"min_age": 18, "gender": "Female", "income_limit": 200000},
        "source_url": "https://www.pmuy.gov.in",
    },
    {
        "id": "SCH_029",
        "name": "Lakhpati Didi Scheme (NRLM - Women SHGs)",
        "issuing_body": "Ministry of Rural Development",
        "state": None,
        "category": "Women & Child",
        "description": "Financial enablement, technical training, digital marketing, and interest-subvented loans for women members of Deendayal Antyodaya Yojana - NRLM Self Help Groups (SHGs) to earn at least ₹1,00,000 annually.",
        "eligibility_rules": {"min_age": 18, "gender": "Female", "shg_member": True},
        "source_url": "https://nrlm.gov.in",
    },
    {
        "id": "SCH_030",
        "name": "Beti Bachao Beti Padhao (BBBP)",
        "issuing_body": "Ministry of Women and Child Development",
        "state": None,
        "category": "Women & Child",
        "description": "Comprehensive national campaign ensuring survival, protection, and quality primary to higher secondary education for girl children across all Indian districts.",
        "eligibility_rules": {"gender": "Female"},
        "source_url": "https://wcd.nic.in",
    },

    # ==========================================
    # CENTRAL GOVERNMENT: HOUSING & INFRASTRUCTURE
    # ==========================================
    {
        "id": "SCH_031",
        "name": "Pradhan Mantri Awas Yojana - Gramin (PMAY-G)",
        "issuing_body": "Ministry of Rural Development",
        "state": None,
        "category": "Housing & Urban",
        "description": "Financial grant assistance of ₹1,20,000 in plain areas and ₹1,30,000 in hilly/difficult areas along with 90 days MGNREGA wages and ₹12,000 for toilet construction to build a permanent pucca house.",
        "eligibility_rules": {"income_limit": 200000, "homeless_or_kutcha_house": True},
        "source_url": "https://pmayg.nic.in",
    },
    {
        "id": "SCH_032",
        "name": "Pradhan Mantri Awas Yojana - Urban (PMAY-U 2.0)",
        "issuing_body": "Ministry of Housing and Urban Affairs",
        "state": None,
        "category": "Housing & Urban",
        "description": "Interest subsidy up to ₹1,80,000 and direct central financial assistance of up to ₹2.5 Lakh for EWS/LIG families to construct, purchase, or renovate an urban house.",
        "eligibility_rules": {"income_limit": 600000, "no_pucca_house": True},
        "source_url": "https://pmaymis.gov.in",
    },
    {
        "id": "SCH_033",
        "name": "PM Surya Ghar: Muft Bijli Yojana (Rooftop Solar Subsidy)",
        "issuing_body": "Ministry of New and Renewable Energy",
        "state": None,
        "category": "Renewable Energy",
        "description": "Direct central subsidy up to ₹78,000 for residential rooftop solar installations up to 3 kW capacity, providing up to 300 units of free electricity every month.",
        "eligibility_rules": {"residential_power_connection": True},
        "source_url": "https://pmsuryaghar.gov.in",
    },
    {
        "id": "SCH_034",
        "name": "PM KUSUM Scheme (Solar Agriculture Pumps)",
        "issuing_body": "Ministry of New and Renewable Energy",
        "state": None,
        "category": "Renewable Energy",
        "description": "Up to 60% combined subsidy (30% Central + 30% State) for farmers to replace diesel irrigation pumps with standalone solar water pumps and solarize existing grid-connected pumps.",
        "eligibility_rules": {"is_farmer": True},
        "source_url": "https://pmkusum.mnre.gov.in",
    },

    # ==========================================
    # CENTRAL GOVERNMENT: SOCIAL SECURITY & PENSIONS
    # ==========================================
    {
        "id": "SCH_035",
        "name": "Atal Pension Yojana (APY)",
        "issuing_body": "Pension Fund Regulatory and Development Authority (PFRDA)",
        "state": None,
        "category": "Social Justice & Pension",
        "description": "Guaranteed monthly pension of ₹1,000, ₹2,000, ₹3,000, ₹4,000, or ₹5,000 after reaching age 60 for unorganized sector workers based on monthly contributions starting from age 18 to 40.",
        "eligibility_rules": {"min_age": 18, "max_age": 40, "non_taxpayer": True},
        "source_url": "https://enps.nsdl.com",
    },
    {
        "id": "SCH_036",
        "name": "Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)",
        "issuing_body": "Ministry of Finance",
        "state": None,
        "category": "Social Justice & Pension",
        "description": "Life insurance term cover of ₹2,00,000 on death due to any cause for an affordable annual premium of ₹436 debited automatically from the bank account.",
        "eligibility_rules": {"min_age": 18, "max_age": 50},
        "source_url": "https://www.jansuraksha.gov.in",
    },
    {
        "id": "SCH_037",
        "name": "Pradhan Mantri Suraksha Bima Yojana (PMSBY)",
        "issuing_body": "Ministry of Finance",
        "state": None,
        "category": "Social Justice & Pension",
        "description": "Accidental death and full disability insurance cover of ₹2,00,000 (and ₹1,00,000 for partial disability) for a nominal premium of just ₹20 per year.",
        "eligibility_rules": {"min_age": 18, "max_age": 70},
        "source_url": "https://www.jansuraksha.gov.in",
    },
    {
        "id": "SCH_038",
        "name": "Indira Gandhi National Old Age Pension Scheme (IGNOAPS)",
        "issuing_body": "Ministry of Rural Development",
        "state": None,
        "category": "Social Justice & Pension",
        "description": "Monthly pension assistance for destitute senior citizens living below the poverty line (BPL), supplemented with matching state government contributions.",
        "eligibility_rules": {"min_age": 60, "income_limit": 100000, "bpl_status": True},
        "source_url": "https://nsap.nic.in",
    },
    {
        "id": "SCH_039",
        "name": "Indira Gandhi National Widow Pension Scheme (IGNWPS)",
        "issuing_body": "Ministry of Rural Development",
        "state": None,
        "category": "Social Justice & Pension",
        "description": "Monthly financial pension for widowed women living below the poverty line to ensure dignified livelihood and social security.",
        "eligibility_rules": {"min_age": 40, "max_age": 79, "gender": "Female", "marital_status": "Widow", "bpl_status": True},
        "source_url": "https://nsap.nic.in",
    },
    {
        "id": "SCH_040",
        "name": "Indira Gandhi National Disability Pension Scheme (IGNDPS)",
        "issuing_body": "Ministry of Rural Development",
        "state": None,
        "category": "Disability & Inclusion",
        "description": "Monthly pension support for severely and profoundly disabled individuals (80%+ disability or multiple disabilities) living below the poverty line.",
        "eligibility_rules": {"min_age": 18, "min_disability_percent": 80, "bpl_status": True},
        "source_url": "https://nsap.nic.in",
    },
    {
        "id": "SCH_041",
        "name": "ADIP Scheme (Assistance to Disabled Persons for Aids & Appliances)",
        "issuing_body": "Ministry of Social Justice and Empowerment",
        "state": None,
        "category": "Disability & Inclusion",
        "description": "Free distribution of modern, scientifically manufactured aids and assistive appliances (wheelchairs, motorized tricycles, hearing aids, prosthetic limbs, braille kits) to disabled persons.",
        "eligibility_rules": {"min_disability_percent": 40, "income_limit": 360000},
        "source_url": "https://alimco.in",
    },
    {
        "id": "SCH_042",
        "name": "PM Shram Yogi Maandhan Yojana (PM-SYM - Unorganized Worker Pension)",
        "issuing_body": "Ministry of Labour and Employment",
        "state": None,
        "category": "Labour & Employment",
        "description": "Assured monthly pension of ₹3,000 after age 60 for unorganized workers (rickshaw pullers, domestic workers, construction workers, agricultural laborers) with monthly income under ₹15,000.",
        "eligibility_rules": {"min_age": 18, "max_age": 40, "income_limit": 180000},
        "source_url": "https://maandhan.in",
    },
    {
        "id": "SCH_043",
        "name": "e-Shram National Database & Welfare Card",
        "issuing_body": "Ministry of Labour and Employment",
        "state": None,
        "category": "Labour & Employment",
        "description": "12-digit universal UAN card for unorganized workers enabling seamless access to social security schemes, accident insurance cover of ₹2 Lakh, and emergency DBT benefits.",
        "eligibility_rules": {"min_age": 16, "max_age": 59, "non_epfo_esic": True},
        "source_url": "https://eshram.gov.in",
    },

    # ==========================================
    # CENTRAL GOVERNMENT: EDUCATION & SCHOLARSHIPS
    # ==========================================
    {
        "id": "SCH_044",
        "name": "National Means-cum-Merit Scholarship Scheme (NMMSS)",
        "issuing_body": "Department of School Education and Literacy, Ministry of Education",
        "state": None,
        "category": "Education & Scholarships",
        "description": "Scholarship of ₹12,000 per annum (₹1,000 per month) for meritorious economically weaker students from class 9 to 12 to prevent secondary dropout.",
        "eligibility_rules": {"income_limit": 350000, "class_range": "Class 9-12"},
        "source_url": "https://scholarships.gov.in",
    },
    {
        "id": "SCH_045",
        "name": "Post-Matric Scholarship Scheme for SC Students (Centrally Sponsored)",
        "issuing_body": "Ministry of Social Justice and Empowerment",
        "state": None,
        "category": "Education & Scholarships",
        "description": "100% compulsory non-refundable fees reimbursement plus monthly maintenance allowance up to ₹13,500/year for SC students pursuing post-matric / college / university courses.",
        "eligibility_rules": {"caste_categories": ["SC"], "income_limit": 250000},
        "source_url": "https://scholarships.gov.in",
    },
    {
        "id": "SCH_046",
        "name": "Post-Matric Scholarship for OBC / EBC / DNT Students",
        "issuing_body": "Ministry of Social Justice and Empowerment",
        "state": None,
        "category": "Education & Scholarships",
        "description": "Financial tuition fee and academic maintenance grant for Other Backward Classes (OBC) and Economically Backward Classes (EBC) students studying at college and university level.",
        "eligibility_rules": {"caste_categories": ["OBC", "EBC", "DNT"], "income_limit": 250000},
        "source_url": "https://scholarships.gov.in",
    },
    {
        "id": "SCH_047",
        "name": "National Overseas Scholarship (NOS) for SC / ST / De-Notified Nomadic Tribes",
        "issuing_body": "Ministry of Social Justice and Empowerment",
        "state": None,
        "category": "Education & Scholarships",
        "description": "Full financial scholarship covering entire tuition fees, annual living allowance ($15,400+ or £9,900+), medical insurance, and return airfare for Master's and Ph.D. studies in top foreign universities.",
        "eligibility_rules": {"caste_categories": ["SC", "ST", "DNT"], "income_limit": 800000, "min_score_percent": 60},
        "source_url": "https://nosmsje.gov.in",
    },
    {
        "id": "SCH_048",
        "name": "Pragati Scholarship Scheme for Girl Students (Technical Degree/Diploma - AICTE)",
        "issuing_body": "AICTE, Ministry of Education",
        "state": None,
        "category": "Education & Scholarships",
        "description": "Annual scholarship grant of ₹50,000 per year towards tuition fees, laptop, books, and college hostel expenses for girl students admitted in AICTE approved engineering/diploma colleges.",
        "eligibility_rules": {"gender": "Female", "income_limit": 800000, "course_type": "AICTE Engineering/Technical"},
        "source_url": "https://www.aicte-india.org",
    },
    {
        "id": "SCH_049",
        "name": "Saksham Scholarship Scheme for Specially-Abled Students (AICTE)",
        "issuing_body": "AICTE, Ministry of Education",
        "state": None,
        "category": "Education & Scholarships",
        "description": "Financial scholarship of ₹50,000 per year for disabled students with 40%+ disability studying in AICTE recognized technical colleges and universities.",
        "eligibility_rules": {"min_disability_percent": 40, "income_limit": 800000},
        "source_url": "https://www.aicte-india.org",
    },
    {
        "id": "SCH_050",
        "name": "PM Uchchatar Shiksha Protsahan (PM-USP) Central Sector Scheme",
        "issuing_body": "Department of Higher Education, Ministry of Education",
        "state": None,
        "category": "Education & Scholarships",
        "description": "Direct merit-cum-means scholarship of ₹12,000/year for graduation and ₹20,000/year for post-graduation for top scoring 12th pass students from economically weaker families.",
        "eligibility_rules": {"income_limit": 450000, "min_score_percentile": 80},
        "source_url": "https://scholarships.gov.in",
    },

    # ==========================================
    # CENTRAL GOVERNMENT: MINORITY & TRIBAL AFFAIRS
    # ==========================================
    {
        "id": "SCH_051",
        "name": "National Fellowship and Scholarship for Higher Education of ST Students",
        "issuing_body": "Ministry of Tribal Affairs",
        "state": None,
        "category": "Tribal Welfare",
        "description": "100% financial assistance including full course tuition fees and monthly living allowance for Scheduled Tribe (ST) students pursuing M.Phil, Ph.D., and professional degrees at premier institutes like IITs, IIMs, and AIIMS.",
        "eligibility_rules": {"caste_categories": ["ST"], "income_limit": 600000},
        "source_url": "https://tribal.nic.in",
    },
    {
        "id": "SCH_052",
        "name": "Van Dhan Vikas Yojana (VDVY - Tribal Livelihoods)",
        "issuing_body": "TRIFED, Ministry of Tribal Affairs",
        "state": None,
        "category": "Tribal Welfare",
        "description": "Grant of ₹15 Lakh per Van Dhan SHG Cluster for establishing processing facilities, value-addition, packaging, and marketing of Minor Forest Produce (MFP) collected by tribal forest dwellers.",
        "eligibility_rules": {"caste_categories": ["ST"], "tribal_forest_gatherer": True},
        "source_url": "https://trifed.tribal.gov.in",
    },
    {
        "id": "SCH_053",
        "name": "Pradhan Mantri Jan Vikas Karyakram (PMJVK)",
        "issuing_body": "Ministry of Minority Affairs",
        "state": None,
        "category": "Minority Welfare",
        "description": "Infrastructure development grants for setting up schools, smart classrooms, ITIs, polytechnics, hostels, and primary health centers in minority concentrated areas.",
        "eligibility_rules": {"minority_community": True},
        "source_url": "https://www.minorityaffairs.gov.in",
    },

    # ==========================================
    # STATE SCHEMES: UTTAR PRADESH
    # ==========================================
    {
        "id": "SCH_054",
        "name": "UP Old Age Senior Citizen Pension Scheme (Vridhavastha Pension)",
        "issuing_body": "Social Welfare Department, Government of Uttar Pradesh",
        "state": "Uttar Pradesh",
        "category": "Social Justice & Pension",
        "description": "Direct monthly pension of ₹1,000 (₹3,000 per quarter) directly transferred to bank accounts of senior citizens aged 60 and above living in Uttar Pradesh.",
        "eligibility_rules": {"min_age": 60, "income_limit": 56460, "state": "Uttar Pradesh"},
        "source_url": "https://sspy-up.gov.in",
    },
    {
        "id": "SCH_055",
        "name": "UP Nirashrit Mahila Pension Yojana (Destitute / Widow Pension)",
        "issuing_body": "Women and Child Development, Government of Uttar Pradesh",
        "state": "Uttar Pradesh",
        "category": "Social Justice & Pension",
        "description": "Financial assistance of ₹1,000 per month for destitute widowed women residing in UP with no family breadwinner.",
        "eligibility_rules": {"min_age": 18, "gender": "Female", "marital_status": "Widow", "income_limit": 200000, "state": "Uttar Pradesh"},
        "source_url": "https://sspy-up.gov.in",
    },
    {
        "id": "SCH_056",
        "name": "UP Divyangjan Pension Yojana (Disability Pension)",
        "issuing_body": "Divyangjan Empowerment Department, Government of Uttar Pradesh",
        "state": "Uttar Pradesh",
        "category": "Disability & Inclusion",
        "description": "Monthly financial pension of ₹1,000 directly transferred to UP residents with 40% or higher certified physical/mental disability.",
        "eligibility_rules": {"min_age": 18, "min_disability_percent": 40, "income_limit": 56460, "state": "Uttar Pradesh"},
        "source_url": "https://sspy-up.gov.in",
    },
    {
        "id": "SCH_057",
        "name": "UP Gopalak Yojana (Dairy Animal Husbandry Loan & Subsidy)",
        "issuing_body": "Animal Husbandry Department, Government of Uttar Pradesh",
        "state": "Uttar Pradesh",
        "category": "Agriculture",
        "description": "Bank loan facility up to ₹9,00,000 with state government interest subsidy up to ₹1,00,000 for purchasing 10-12 high-yielding dairy cows/buffaloes to start a modern dairy unit.",
        "eligibility_rules": {"min_age": 18, "income_limit": 100000, "state": "Uttar Pradesh"},
        "source_url": "https://animalhusb.upsdc.gov.in",
    },
    {
        "id": "SCH_058",
        "name": "UP Mukhyamantri Kanya Sumangala Yojana",
        "issuing_body": "Women and Child Development, Government of Uttar Pradesh",
        "state": "Uttar Pradesh",
        "category": "Women & Child",
        "description": "Financial assistance of ₹25,000 in 6 progressive installments from birth, vaccination, school admissions (Class 1, 6, 9) up to 2-year graduation/diploma for girl children in UP.",
        "eligibility_rules": {"gender": "Female", "income_limit": 300000, "state": "Uttar Pradesh"},
        "source_url": "https://mksy.up.gov.in",
    },
    {
        "id": "SCH_059",
        "name": "UP Mukhyamantri Abhyudaya Yojana (Free Competitive Exam Coaching)",
        "issuing_body": "Social Welfare Department, Government of Uttar Pradesh",
        "state": "Uttar Pradesh",
        "category": "Education & Scholarships",
        "description": "Free offline and online high-quality coaching, study materials, and free tablets for UP youth preparing for UPSC, UPPSC, JEE, NEET, NDA, CDS, and bank examinations.",
        "eligibility_rules": {"state": "Uttar Pradesh"},
        "source_url": "http://abhyuday.up.gov.in",
    },
    {
        "id": "SCH_060",
        "name": "UP Mukhyamantri Yuva Swarojgar Yojana (Self-Employment Loan Subsidy)",
        "issuing_body": "Department of MSME and Export Promotion, Government of Uttar Pradesh",
        "state": "Uttar Pradesh",
        "category": "MSME & Business",
        "description": "Bank loans up to ₹25 Lakh for setting up manufacturing industries and ₹10 Lakh for service units with 25% margin money subsidy (maximum ₹6.25 Lakh) from the UP Government.",
        "eligibility_rules": {"min_age": 18, "max_age": 40, "min_education": "10th Pass", "state": "Uttar Pradesh"},
        "source_url": "https://diupmsme.upsdc.gov.in",
    },
    {
        "id": "SCH_061",
        "name": "UP One District One Product (ODOP) Margin Money Scheme",
        "issuing_body": "Department of MSME, Government of Uttar Pradesh",
        "state": "Uttar Pradesh",
        "category": "MSME & Business",
        "description": "Subsidy ranging from 10% to 25% on project costs (up to ₹20 Lakh) for establishing or upgrading specialized ODOP artisan and manufacturing units in designated UP districts.",
        "eligibility_rules": {"min_age": 18, "state": "Uttar Pradesh"},
        "source_url": "https://odopup.in",
    },

    # ==========================================
    # STATE SCHEMES: BIHAR
    # ==========================================
    {
        "id": "SCH_062",
        "name": "Mukhyamantri Udyami Yojana (Bihar Entrepreneurship Scheme)",
        "issuing_body": "Department of Industries, Government of Bihar",
        "state": "Bihar",
        "category": "MSME & Business",
        "description": "Financial loan-cum-subsidy of ₹10 Lakh (50% grant up to ₹5 Lakh + 50% interest-free loan) for SC, ST, EBC, Women, and Youth of Bihar to start new manufacturing and service businesses.",
        "eligibility_rules": {"min_age": 18, "max_age": 50, "min_education": "12th Pass / ITI", "state": "Bihar"},
        "source_url": "https://udyami.bihar.gov.in",
    },
    {
        "id": "SCH_063",
        "name": "Bihar Student Credit Card Scheme (MNSSBY)",
        "issuing_body": "Education Department, Government of Bihar",
        "state": "Bihar",
        "category": "Education & Scholarships",
        "description": "Education loans up to ₹4,00,000 at 1% interest for women, disabled, and transgender students, and 4% for male students for pursuing higher education degrees in recognized colleges.",
        "eligibility_rules": {"max_age": 25, "min_education": "12th Pass", "state": "Bihar"},
        "source_url": "https://www.7nishchay-yuvaupmission.bihar.gov.in",
    },
    {
        "id": "SCH_064",
        "name": "Mukhyamantri Kanya Utthan Yojana (Bihar)",
        "issuing_body": "Social Welfare & Education Department, Government of Bihar",
        "state": "Bihar",
        "category": "Women & Child",
        "description": "Direct financial assistance of up to ₹54,100 from birth up to graduation (₹25,000 on passing 12th unmarried and ₹50,000 on completing graduation) for girl students in Bihar.",
        "eligibility_rules": {"gender": "Female", "state": "Bihar"},
        "source_url": "https://medhasoft.bih.nic.in",
    },
    {
        "id": "SCH_065",
        "name": "Bihar Mukhyamantri Vridhjan Pension Yojana (MVPY)",
        "issuing_body": "Social Welfare Department, Government of Bihar",
        "state": "Bihar",
        "category": "Social Justice & Pension",
        "description": "Universal monthly pension of ₹400 for senior citizens aged 60-79 years and ₹500 for senior citizens aged 80 years and above residing in Bihar.",
        "eligibility_rules": {"min_age": 60, "state": "Bihar"},
        "source_url": "https://sspmis.bihar.gov.in",
    },
    {
        "id": "SCH_066",
        "name": "Bihar Diesel Anudan Yojana for Farmers",
        "issuing_body": "Agriculture Department, Government of Bihar",
        "state": "Bihar",
        "category": "Agriculture",
        "description": "Direct cash subsidy of ₹75 per liter up to ₹750 per acre per irrigation (up to 3 irrigations) to help farmers irrigate standing crops during rainfall deficit.",
        "eligibility_rules": {"is_farmer": True, "state": "Bihar"},
        "source_url": "https://dbtagriculture.bihar.gov.in",
    },

    # ==========================================
    # STATE SCHEMES: MAHARASHTRA
    # ==========================================
    {
        "id": "SCH_067",
        "name": "Mukhyamantri Majhi Ladki Bahin Yojana (Maharashtra)",
        "issuing_body": "Women and Child Development Department, Government of Maharashtra",
        "state": "Maharashtra",
        "category": "Women & Child",
        "description": "Direct financial cash transfer of ₹1,500 every month directly to the bank accounts of women aged 21 to 65 years with annual family income up to ₹2.5 Lakh.",
        "eligibility_rules": {"min_age": 21, "max_age": 65, "gender": "Female", "income_limit": 250000, "state": "Maharashtra"},
        "source_url": "https://ladkibahin.maharashtra.gov.in",
    },
    {
        "id": "SCH_068",
        "name": "Mahatma Jyotirao Phule Jan Arogya Yojana (MJPJAY - Maharashtra)",
        "issuing_body": "Public Health Department, Government of Maharashtra",
        "state": "Maharashtra",
        "category": "Health",
        "description": "Comprehensive cashless medical treatment and surgical coverage up to ₹5,00,000 per family per year for 1,356 medical procedures across empaneled hospitals.",
        "eligibility_rules": {"state": "Maharashtra", "ration_card_holder": True},
        "source_url": "https://www.jeevandayee.gov.in",
    },
    {
        "id": "SCH_069",
        "name": "Namo Shetkari Mahasanman Nidhi Yojana (Maharashtra)",
        "issuing_body": "Agriculture Department, Government of Maharashtra",
        "state": "Maharashtra",
        "category": "Agriculture",
        "description": "Additional state financial benefit of ₹6,000 per year in 3 equal installments given to farmers over and above the Central PM-Kisan scheme, totaling ₹12,000 per year.",
        "eligibility_rules": {"is_farmer": True, "state": "Maharashtra"},
        "source_url": "https://krishi.maharashtra.gov.in",
    },
    {
        "id": "SCH_070",
        "name": "Sanjay Gandhi Niradhar Anudan Yojana (Maharashtra)",
        "issuing_body": "Social Justice and Special Assistance, Government of Maharashtra",
        "state": "Maharashtra",
        "category": "Social Justice & Pension",
        "description": "Financial assistance of ₹1,500 per month to destitute senior citizens, widows, divorcées, disabled persons, and patients with serious illnesses in Maharashtra.",
        "eligibility_rules": {"income_limit": 50000, "state": "Maharashtra"},
        "source_url": "https://sjsa.maharashtra.gov.in",
    },
    {
        "id": "SCH_071",
        "name": "Dr. Punjabrao Deshmukh Vastigruh Nirvah Bhatta Yojna (Maharashtra)",
        "issuing_body": "Higher and Technical Education Department, Government of Maharashtra",
        "state": "Maharashtra",
        "category": "Education & Scholarships",
        "description": "Hostel maintenance allowance up to ₹30,000 per year for children of registered agricultural laborers and marginal farmers pursuing technical/higher education degrees.",
        "eligibility_rules": {"income_limit": 800000, "state": "Maharashtra"},
        "source_url": "https://mahadbt.maharashtra.gov.in",
    },

    # ==========================================
    # STATE SCHEMES: RAJASTHAN
    # ==========================================
    {
        "id": "SCH_072",
        "name": "Mukhyamantri Chiranjeevi Swasthya Bima Yojana (Rajasthan Ayushman)",
        "issuing_body": "Medical, Health & Family Welfare, Government of Rajasthan",
        "state": "Rajasthan",
        "category": "Health",
        "description": "Universal cashless healthcare hospitalization insurance cover up to ₹25 Lakh per family per year along with ₹10 Lakh accidental insurance.",
        "eligibility_rules": {"state": "Rajasthan"},
        "source_url": "https://chiranjeevi.rajasthan.gov.in",
    },
    {
        "id": "SCH_073",
        "name": "Mukhyamantri Anuprati Coaching Yojana (Rajasthan)",
        "issuing_body": "Social Justice and Empowerment Department, Government of Rajasthan",
        "state": "Rajasthan",
        "category": "Education & Scholarships",
        "description": "Free coaching for 30,000 meritorious students from SC, ST, OBC, EWS, and minority categories for UPSC, RPSC, REET, NEET, IIT-JEE, and CLAT with ₹40,000 annual accommodation allowance for outstation candidates.",
        "eligibility_rules": {"income_limit": 800000, "state": "Rajasthan"},
        "source_url": "https://sjrms.rajasthan.gov.in",
    },
    {
        "id": "SCH_074",
        "name": "Rajasthan Indira Gandhi Matritva Poshan Yojana (IGMPY)",
        "issuing_body": "Women and Child Development Department, Government of Rajasthan",
        "state": "Rajasthan",
        "category": "Women & Child",
        "description": "Cash incentive of ₹6,000 in 5 installments directly to pregnant women on the birth of their second child to improve nutritional outcomes.",
        "eligibility_rules": {"gender": "Female", "is_pregnant_or_lactating": True, "state": "Rajasthan"},
        "source_url": "https://wcd.rajasthan.gov.in",
    },
    {
        "id": "SCH_075",
        "name": "Mukhyamantri Vridhjan Samman Pension Yojana (Rajasthan)",
        "issuing_body": "Social Justice and Empowerment, Government of Rajasthan",
        "state": "Rajasthan",
        "category": "Social Justice & Pension",
        "description": "Guaranteed minimum monthly pension of ₹1,150 (with 15% automatic annual increment) for women aged 55+ and men aged 58+ residing in Rajasthan.",
        "eligibility_rules": {"min_age": 55, "income_limit": 48000, "state": "Rajasthan"},
        "source_url": "https://ssp.rajasthan.gov.in",
    },
    {
        "id": "SCH_076",
        "name": "Rajasthan Kisan Mahotsav & Krishi Yantra Subsidy",
        "issuing_body": "Department of Agriculture, Government of Rajasthan",
        "state": "Rajasthan",
        "category": "Agriculture",
        "description": "Subsidies ranging from 40% to 50% for purchasing agricultural implements (rotavators, seed drills, thresher machines, drip lines) for Rajasthan farmers.",
        "eligibility_rules": {"is_farmer": True, "state": "Rajasthan"},
        "source_url": "https://rajkisan.rajasthan.gov.in",
    },

    # ==========================================
    # STATE SCHEMES: MADHYA PRADESH
    # ==========================================
    {
        "id": "SCH_077",
        "name": "Mukhyamantri Ladli Behna Yojana (Madhya Pradesh)",
        "issuing_body": "Women and Child Development Department, Government of Madhya Pradesh",
        "state": "Madhya Pradesh",
        "category": "Women & Child",
        "description": "Direct cash transfer of ₹1,250 every month directly to the bank accounts of married/widowed/divorced women aged 21 to 60 with family income below ₹2.5 Lakh.",
        "eligibility_rules": {"min_age": 21, "max_age": 60, "gender": "Female", "income_limit": 250000, "state": "Madhya Pradesh"},
        "source_url": "https://cmladlibahna.mp.gov.in",
    },
    {
        "id": "SCH_078",
        "name": "Mukhyamantri Kisan Kalyan Yojana (Madhya Pradesh)",
        "issuing_body": "Farmer Welfare and Agriculture Development, Government of Madhya Pradesh",
        "state": "Madhya Pradesh",
        "category": "Agriculture",
        "description": "Direct financial aid of ₹6,000 per year in three installments of ₹2,000 each to eligible farmers in MP over and above the Central PM-Kisan scheme (Total ₹12,000/year).",
        "eligibility_rules": {"is_farmer": True, "state": "Madhya Pradesh"},
        "source_url": "https://saara.mp.gov.in",
    },
    {
        "id": "SCH_079",
        "name": "Mukhyamantri Seekho-Kamao Yojana (MMSKY - Learn and Earn Scheme)",
        "issuing_body": "Technical Education, Skill Development and Employment, Government of MP",
        "state": "Madhya Pradesh",
        "category": "Skill Development",
        "description": "On-the-job industrial skill training for youth aged 18 to 29 with monthly stipend of ₹8,000 (12th pass), ₹8,500 (ITI), ₹9,000 (Diploma), and ₹10,000 (Graduates/Post-graduates).",
        "eligibility_rules": {"min_age": 18, "max_age": 29, "min_education": "12th Pass", "state": "Madhya Pradesh"},
        "source_url": "https://mmsky.mp.gov.in",
    },
    {
        "id": "SCH_080",
        "name": "MP Sambal 2.0 Yojana (Jan Kalyan Sambal Scheme)",
        "issuing_body": "Labour Department, Government of Madhya Pradesh",
        "state": "Madhya Pradesh",
        "category": "Labour & Employment",
        "description": "Comprehensive social security for unorganized workers including ₹16,000 maternity assistance, free education for children, ₹2 Lakh for normal death, and ₹4 Lakh for accidental death.",
        "eligibility_rules": {"min_age": 18, "max_age": 60, "state": "Madhya Pradesh", "unorganized_worker": True},
        "source_url": "https://sambal.mp.gov.in",
    },

    # ==========================================
    # STATE SCHEMES: TAMIL NADU
    # ==========================================
    {
        "id": "SCH_081",
        "name": "Kalaignar Magalir Urimai Thittam (Tamil Nadu Women Basic Income Scheme)",
        "issuing_body": "Special Programme Implementation Department, Government of Tamil Nadu",
        "state": "Tamil Nadu",
        "category": "Women & Child",
        "description": "Monthly rights grant of ₹1,000 directly transferred to 1.15+ crore female heads of households with annual income under ₹2.5 Lakh and landholding under 5 acres.",
        "eligibility_rules": {"min_age": 21, "gender": "Female", "income_limit": 250000, "state": "Tamil Nadu"},
        "source_url": "https://kmut.tn.gov.in",
    },
    {
        "id": "SCH_082",
        "name": "Pudhumai Penn Scheme (Moovalur Ramamirtham Ammaiyar Higher Education)",
        "issuing_body": "Social Welfare and Women Empowerment, Government of Tamil Nadu",
        "state": "Tamil Nadu",
        "category": "Education & Scholarships",
        "description": "Monthly financial assistance of ₹1,000 directly to girl students who studied classes 6 to 12 in government schools until they complete their undergraduate degree, diploma, or ITI.",
        "eligibility_rules": {"gender": "Female", "studied_in_govt_school": True, "state": "Tamil Nadu"},
        "source_url": "https://www.pudhumaipenn.tn.gov.in",
    },
    {
        "id": "SCH_083",
        "name": "Tamil Pudhalvan Scheme (Boys Higher Education Assistance)",
        "issuing_body": "Social Welfare Department, Government of Tamil Nadu",
        "state": "Tamil Nadu",
        "category": "Education & Scholarships",
        "description": "Monthly financial aid of ₹1,000 directly to male students who studied in government schools (classes 6-12) to pursue college and polytechnic education.",
        "eligibility_rules": {"gender": "Male", "studied_in_govt_school": True, "state": "Tamil Nadu"},
        "source_url": "https://www.tn.gov.in",
    },
    {
        "id": "SCH_084",
        "name": "Chief Minister's Comprehensive Health Insurance Scheme (CMCHIS - Tamil Nadu)",
        "issuing_body": "Health and Family Welfare Department, Government of Tamil Nadu",
        "state": "Tamil Nadu",
        "category": "Health",
        "description": "Cashless hospitalization coverage of up to ₹5,00,000 per family per year for 1,090 surgical and medical procedures in government and private empaneled hospitals.",
        "eligibility_rules": {"income_limit": 120000, "state": "Tamil Nadu"},
        "source_url": "https://www.cmchistn.com",
    },
    {
        "id": "SCH_085",
        "name": "Illam Thedi Kalvi (Education at Doorstep Scheme - TN)",
        "issuing_body": "School Education Department, Government of Tamil Nadu",
        "state": "Tamil Nadu",
        "category": "Education & Scholarships",
        "description": "Free community-based evening supplementary education and learning support for primary and middle school children across Tamil Nadu villages.",
        "eligibility_rules": {"state": "Tamil Nadu", "class_range": "Class 1-8"},
        "source_url": "https://illamthedikalvi.tnschools.gov.in",
    },

    # ==========================================
    # STATE SCHEMES: WEST BENGAL
    # ==========================================
    {
        "id": "SCH_086",
        "name": "Lakshmir Bhandar Scheme (West Bengal)",
        "issuing_body": "Department of Women & Child Development and Social Welfare, West Bengal",
        "state": "West Bengal",
        "category": "Women & Child",
        "description": "Direct monthly financial support of ₹1,200 for SC/ST women and ₹1,000 for general category women aged 25 to 60 years heading families in West Bengal.",
        "eligibility_rules": {"min_age": 25, "max_age": 60, "gender": "Female", "state": "West Bengal"},
        "source_url": "https://wb.gov.in",
    },
    {
        "id": "SCH_087",
        "name": "Krishak Bandhu (Natun) Scheme (West Bengal)",
        "issuing_body": "Agriculture Department, Government of West Bengal",
        "state": "West Bengal",
        "category": "Agriculture",
        "description": "Financial assistance of ₹10,000 per acre per year in two equal installments (Kharif and Rabi) along with ₹2,00,000 death benefit for farmer families.",
        "eligibility_rules": {"is_farmer": True, "state": "West Bengal"},
        "source_url": "https://krishakbandhu.wb.gov.in",
    },
    {
        "id": "SCH_088",
        "name": "Kanyashree Prakalpa (West Bengal)",
        "issuing_body": "Department of Women & Child Development, West Bengal",
        "state": "West Bengal",
        "category": "Women & Child",
        "description": "Annual scholarship of ₹1,000 (K1) for unmarried girls aged 13-18 studying in classes 8-12, and a one-time grant of ₹25,000 (K2) upon turning 18 for higher education.",
        "eligibility_rules": {"min_age": 13, "max_age": 19, "gender": "Female", "marital_status": "Unmarried", "state": "West Bengal"},
        "source_url": "https://www.wbkanyashree.gov.in",
    },
    {
        "id": "SCH_089",
        "name": "Swasthya Sathi Scheme (West Bengal)",
        "issuing_body": "Health and Family Welfare Department, Government of West Bengal",
        "state": "West Bengal",
        "category": "Health",
        "description": "Universal cashless healthcare smart card issued in the name of the woman head of the family providing basic secondary and tertiary medical cover up to ₹5,00,000 per year.",
        "eligibility_rules": {"state": "West Bengal"},
        "source_url": "https://swasthyasathi.gov.in",
    },
    {
        "id": "SCH_090",
        "name": "West Bengal Student Credit Card Scheme",
        "issuing_body": "Higher Education Department, Government of West Bengal",
        "state": "West Bengal",
        "category": "Education & Scholarships",
        "description": "Soft education loans up to ₹10,00,000 with 4% simple interest rate and 15 years repayment period for higher studies in India or abroad.",
        "eligibility_rules": {"max_age": 40, "min_education": "10th Pass", "state": "West Bengal"},
        "source_url": "https://wbscc.wb.gov.in",
    },

    # ==========================================
    # STATE SCHEMES: KARNATAKA
    # ==========================================
    {
        "id": "SCH_091",
        "name": "Gruha Lakshmi Scheme (Karnataka)",
        "issuing_body": "Women and Child Development Department, Government of Karnataka",
        "state": "Karnataka",
        "category": "Women & Child",
        "description": "Monthly direct benefit cash assistance of ₹2,000 directly transferred into the bank account of the designated woman head of household in Karnataka.",
        "eligibility_rules": {"gender": "Female", "non_taxpayer": True, "state": "Karnataka"},
        "source_url": "https://sevasindhugs.karnataka.gov.in",
    },
    {
        "id": "SCH_092",
        "name": "Gruha Jyothi Scheme (200 Units Free Electricity - Karnataka)",
        "issuing_body": "Energy Department, Government of Karnataka",
        "state": "Karnataka",
        "category": "Renewable Energy",
        "description": "Zero electricity bill scheme providing up to 200 units of free domestic household power every month for all domestic consumers in Karnataka.",
        "eligibility_rules": {"domestic_meter_holder": True, "state": "Karnataka"},
        "source_url": "https://sevasindhugs.karnataka.gov.in",
    },
    {
        "id": "SCH_093",
        "name": "Yuva Nidhi Scheme (Unemployment Allowance - Karnataka)",
        "issuing_body": "Skill Development, Entrepreneurship and Livelihood Department, Karnataka",
        "state": "Karnataka",
        "category": "Labour & Employment",
        "description": "Monthly unemployment stipend of ₹3,000 for unemployed Degree graduates and ₹1,500 for unemployed Diploma holders for up to 2 years while seeking jobs.",
        "eligibility_rules": {"max_age": 28, "unemployed": True, "state": "Karnataka"},
        "source_url": "https://sevasindhugs.karnataka.gov.in",
    },
    {
        "id": "SCH_094",
        "name": "Shakti Scheme (Free Bus Travel for Women - Karnataka)",
        "issuing_body": "Transport Department, Government of Karnataka",
        "state": "Karnataka",
        "category": "Women & Child",
        "description": "Free transit in all state-run non-premium road transport corporation buses (KSRTC, BMTC, NWKRTC, KKRTC) for women, girls, and transgender residents of Karnataka.",
        "eligibility_rules": {"gender": "Female", "state": "Karnataka"},
        "source_url": "https://transport.karnataka.gov.in",
    },
    {
        "id": "SCH_095",
        "name": "Anna Bhagya Scheme (Direct Cash for Food Grain - Karnataka)",
        "issuing_body": "Food, Civil Supplies & Consumer Affairs Department, Karnataka",
        "state": "Karnataka",
        "category": "Social Justice & Pension",
        "description": "Direct bank transfer of ₹170 per person per month (equivalent to 5 kg rice at ₹34/kg) for BPL and Antyodaya Anna Yojana ration card beneficiaries.",
        "eligibility_rules": {"bpl_status": True, "state": "Karnataka"},
        "source_url": "https://ahara.kar.nic.in",
    },

    # ==========================================
    # STATE SCHEMES: TELANGANA & ANDHRA PRADESH
    # ==========================================
    {
        "id": "SCH_096",
        "name": "Rythu Bharosa / Rythu Bandhu (Telangana Farmer Investment Support)",
        "issuing_body": "Department of Agriculture, Government of Telangana",
        "state": "Telangana",
        "category": "Agriculture",
        "description": "Direct investment support of ₹15,000 per acre per year (₹7,500 per acre per season) directly to farmers and tenant farmers to purchase seeds, fertilizers, and farm inputs.",
        "eligibility_rules": {"is_farmer": True, "state": "Telangana"},
        "source_url": "https://rythubandhu.telangana.gov.in",
    },
    {
        "id": "SCH_097",
        "name": "Maha Lakshmi Scheme (Telangana Free Bus & ₹2,500 Women Aid)",
        "issuing_body": "Women and Child Welfare Department, Government of Telangana",
        "state": "Telangana",
        "category": "Women & Child",
        "description": "Direct financial aid of ₹2,500 per month for women heading families, free travel in TSRTC buses, and LPG cylinders at ₹500 for poor households.",
        "eligibility_rules": {"gender": "Female", "income_limit": 200000, "state": "Telangana"},
        "source_url": "https://telangana.gov.in",
    },
    {
        "id": "SCH_098",
        "name": "YSR Cheyutha / YSR Sunna Vaddi (Andhra Pradesh Women Welfare)",
        "issuing_body": "Panchayat Raj and Rural Development, Government of Andhra Pradesh",
        "state": "Andhra Pradesh",
        "category": "Women & Child",
        "description": "Financial assistance of ₹18,750 per year for 4 years (total ₹75,000) for SC, ST, BC, and Minority women aged 45 to 60 years to establish sustainable livelihoods.",
        "eligibility_rules": {"min_age": 45, "max_age": 60, "gender": "Female", "caste_categories": ["SC", "ST", "BC", "Minority"], "state": "Andhra Pradesh"},
        "source_url": "https://navasakam.ap.gov.in",
    },
    {
        "id": "SCH_099",
        "name": "YSR Jagananna Vidya Deevena (Full Fee Reimbursement - AP)",
        "issuing_body": "Higher Education Department, Government of Andhra Pradesh",
        "state": "Andhra Pradesh",
        "category": "Education & Scholarships",
        "description": "100% complete fee reimbursement credited directly to the accounts of mothers of college students pursuing ITI, Polytechnic, Degree, Engineering, and Pharmacy courses.",
        "eligibility_rules": {"income_limit": 250000, "state": "Andhra Pradesh"},
        "source_url": "https://jaganannavydeeveena.ap.gov.in",
    },
    {
        "id": "SCH_100",
        "name": "YSR Rythu Bharosa - PM KISAN (Andhra Pradesh)",
        "issuing_body": "Agriculture and Cooperation Department, Government of Andhra Pradesh",
        "state": "Andhra Pradesh",
        "category": "Agriculture",
        "description": "Financial assistance of ₹13,500 per year (including Central PM-Kisan) directly to farmer and tenant farmer families before Kharif and Rabi sowing seasons.",
        "eligibility_rules": {"is_farmer": True, "state": "Andhra Pradesh"},
        "source_url": "https://ysrrythubharosa.ap.gov.in",
    },

    # ==========================================
    # STATE SCHEMES: GUJARAT
    # ==========================================
    {
        "id": "SCH_101",
        "name": "Mukhyamantri Amrutam (MA) & MA Vatsalya Yojana (Gujarat)",
        "issuing_body": "Health and Family Welfare Department, Government of Gujarat",
        "state": "Gujarat",
        "category": "Health",
        "description": "Cashless medical insurance coverage up to ₹10,00,000 per family per year for catastrophic illnesses, cardiology, oncology, and neurosurgery in empaneled hospitals.",
        "eligibility_rules": {"income_limit": 400000, "state": "Gujarat"},
        "source_url": "https://magujarat.com",
    },
    {
        "id": "SCH_102",
        "name": "Mukhyamantri Kisan Sahay Yojana (MKSY - Gujarat)",
        "issuing_body": "Agriculture, Farmers Welfare & Co-operation Department, Gujarat",
        "state": "Gujarat",
        "category": "Agriculture",
        "description": "Direct zero-premium crop compensation assistance up to ₹25,000 per hectare for farmers facing crop damage due to drought, unseasonal heavy rainfall, or pest attacks.",
        "eligibility_rules": {"is_farmer": True, "state": "Gujarat"},
        "source_url": "https://ikhedut.gujarat.gov.in",
    },
    {
        "id": "SCH_103",
        "name": "Vahli Dikri Yojana (Gujarat Dear Daughter Scheme)",
        "issuing_body": "Women and Child Development Department, Government of Gujarat",
        "state": "Gujarat",
        "category": "Women & Child",
        "description": "Financial assistance of ₹1,10,000 in total (₹4,000 on Class 1 admission, ₹6,000 on Class 9 admission, and ₹1,00,000 upon reaching 18 years) for girl children in Gujarat.",
        "eligibility_rules": {"gender": "Female", "income_limit": 200000, "state": "Gujarat"},
        "source_url": "https://wcd.gujarat.gov.in",
    },
    {
        "id": "SCH_104",
        "name": "Manav Garima Yojana (Gujarat Self-Employment Toolkits)",
        "issuing_body": "Social Justice and Empowerment Department, Government of Gujarat",
        "state": "Gujarat",
        "category": "MSME & Business",
        "description": "Free business toolkits, tailoring machines, electrical and plumbing kits worth up to ₹25,000 for artisans, barbers, tailors, and micro-entrepreneurs from backward classes.",
        "eligibility_rules": {"income_limit": 150000, "state": "Gujarat"},
        "source_url": "https://sje.gujarat.gov.in",
    },
    {
        "id": "SCH_105",
        "name": "Mukhyamantri Yuva Swavalamban Yojana (MYSY - Gujarat Scholarship)",
        "issuing_body": "Education Department, Government of Gujarat",
        "state": "Gujarat",
        "category": "Education & Scholarships",
        "description": "Higher education scholarship covering 50% tuition fees (up to ₹2 Lakh/year for medical/dental and ₹50,000 for engineering) plus ₹12,000/year hostel assistance for meritorious students with 80%+ in 12th.",
        "eligibility_rules": {"income_limit": 600000, "min_score_percent": 80, "state": "Gujarat"},
        "source_url": "https://mysy.guj.nic.in",
    },

    # ==========================================
    # STATE SCHEMES: PUNJAB & HARYANA
    # ==========================================
    {
        "id": "SCH_106",
        "name": "Mukh Mantri Sehat Bima Yojana (Punjab Ayushman)",
        "issuing_body": "Department of Health and Family Welfare, Government of Punjab",
        "state": "Punjab",
        "category": "Health",
        "description": "Cashless secondary and tertiary hospitalization cover up to ₹5,00,000 per family per year for smart ration card holders, farmers (J-Form holders), construction workers, and small traders in Punjab.",
        "eligibility_rules": {"state": "Punjab"},
        "source_url": "https://sha.punjab.gov.in",
    },
    {
        "id": "SCH_107",
        "name": "Ashirwad Scheme (Shagun Scheme for Marriage - Punjab)",
        "issuing_body": "Department of Social Justice, Empowerment and Minorities, Punjab",
        "state": "Punjab",
        "category": "Social Justice & Pension",
        "description": "One-time financial grant of ₹51,000 for the marriage of girls belonging to SC, BC, Christian, and economically weaker families in Punjab.",
        "eligibility_rules": {"gender": "Female", "income_limit": 32790, "state": "Punjab"},
        "source_url": "https://socgen.punjab.gov.in",
    },
    {
        "id": "SCH_108",
        "name": "Bhavantar Bharpayee Yojana (Haryana Price Deficit Subsidy)",
        "issuing_body": "Department of Agriculture and Farmers Welfare, Government of Haryana",
        "state": "Haryana",
        "category": "Agriculture",
        "description": "Direct cash transfer compensating farmers for the difference between market wholesale price and government protected base price for horticultural crops, vegetables, and millet.",
        "eligibility_rules": {"is_farmer": True, "state": "Haryana"},
        "source_url": "https://fasal.haryana.gov.in",
    },
    {
        "id": "SCH_109",
        "name": "Mukhyamantri Parivar Samridhi Yojana (MMPSY - Haryana)",
        "issuing_body": "Finance Department, Government of Haryana",
        "state": "Haryana",
        "category": "Social Justice & Pension",
        "description": "Annual financial security benefit of ₹6,000 per family for families with annual income up to ₹1,80,000 and landholding up to 5 acres to cover life/accident insurance premiums and pensions.",
        "eligibility_rules": {"income_limit": 180000, "max_land_size_hectares": 2.0, "state": "Haryana"},
        "source_url": "https://cm-psy.haryana.gov.in",
    },

    # ==========================================
    # STATE SCHEMES: ODISHA
    # ==========================================
    {
        "id": "SCH_110",
        "name": "KALIA Scheme (Krushak Assistance for Livelihood and Income Augmentation - Odisha)",
        "issuing_body": "Department of Agriculture and Farmers' Empowerment, Government of Odisha",
        "state": "Odisha",
        "category": "Agriculture",
        "description": "Financial assistance of ₹10,000 per year (₹5,000 per season) directly to small, marginal farmers, landless agricultural households, and vulnerable sharecroppers in Odisha.",
        "eligibility_rules": {"is_farmer": True, "state": "Odisha"},
        "source_url": "https://kalia.odisha.gov.in",
    },
    {
        "id": "SCH_111",
        "name": "Biju Swasthya Kalyan Yojana (BSKY - Odisha)",
        "issuing_body": "Health and Family Welfare Department, Government of Odisha",
        "state": "Odisha",
        "category": "Health",
        "description": "Cashless healthcare smart card providing ₹5,00,000 for male family members and ₹10,00,000 for female family members per year in 800+ empaneled private super-specialty hospitals.",
        "eligibility_rules": {"state": "Odisha", "ration_card_holder": True},
        "source_url": "https://bsky.odisha.gov.in",
    },
    {
        "id": "SCH_112",
        "name": "Madhu Babu Pension Yojana (MBPY - Odisha)",
        "issuing_body": "Social Security & Empowerment of Persons with Disabilities, Odisha",
        "state": "Odisha",
        "category": "Social Justice & Pension",
        "description": "Monthly pension assistance ranging from ₹1,000 to ₹1,200 per month for destitute senior citizens, widows, disabled persons, and leprosy patients in Odisha.",
        "eligibility_rules": {"min_age": 60, "income_limit": 40000, "state": "Odisha"},
        "source_url": "https://ssepd.odisha.gov.in",
    },
    {
        "id": "SCH_113",
        "name": "Subhadra Yojana (Odisha Women Empowerment Scheme)",
        "issuing_body": "Women and Child Development Department, Government of Odisha",
        "state": "Odisha",
        "category": "Women & Child",
        "description": "Financial voucher benefit of ₹50,000 over 5 years (₹10,000 per year in two equal installments) for adult women aged 21 to 60 years across Odisha.",
        "eligibility_rules": {"min_age": 21, "max_age": 60, "gender": "Female", "state": "Odisha"},
        "source_url": "https://subhadra.odisha.gov.in",
    },

    # ==========================================
    # STATE SCHEMES: KERALA
    # ==========================================
    {
        "id": "SCH_114",
        "name": "Karunya Arogya Suraksha Padhathi (KASP - Kerala)",
        "issuing_body": "State Health Agency, Health and Family Welfare Department, Kerala",
        "state": "Kerala",
        "category": "Health",
        "description": "Comprehensive health insurance cover of ₹5,00,000 per family per year for secondary and tertiary care across government and empaneled private hospitals.",
        "eligibility_rules": {"state": "Kerala", "bpl_status": True},
        "source_url": "https://sha.kerala.gov.in",
    },
    {
        "id": "SCH_115",
        "name": "Kerala Social Security Welfare Pension (Senior Citizens)",
        "issuing_body": "Finance Department, Government of Kerala",
        "state": "Kerala",
        "category": "Social Justice & Pension",
        "description": "Direct monthly pension of ₹1,600 delivered directly to the homes/bank accounts of senior citizens aged 60 and above with annual family income up to ₹1 Lakh.",
        "eligibility_rules": {"min_age": 60, "income_limit": 100000, "state": "Kerala"},
        "source_url": "https://welfarepension.lsgkerala.gov.in",
    },
    {
        "id": "SCH_116",
        "name": "Subhiksha Keralam (Integrated Agriculture & Food Security)",
        "issuing_body": "Department of Agriculture Development & Farmers' Welfare, Kerala",
        "state": "Kerala",
        "category": "Agriculture",
        "description": "Subsidy support up to 50% for fallow land cultivation, high-tech polyhouses, precision farming, and rooftop organic vegetable gardening in Kerala.",
        "eligibility_rules": {"state": "Kerala"},
        "source_url": "https://keralaagriculture.gov.in",
    },

    # ==========================================
    # STATE SCHEMES: ASSAM & NORTH EAST
    # ==========================================
    {
        "id": "SCH_117",
        "name": "Orunodoi 3.0 Scheme (Assam Direct Benefit Transfer)",
        "issuing_body": "Finance Department, Government of Assam",
        "state": "Assam",
        "category": "Women & Child",
        "description": "Monthly direct benefit cash assistance of ₹1,250 directly to bank accounts of women nominated as the head of low-income families in Assam to cover medicines, pulses, and sugar.",
        "eligibility_rules": {"gender": "Female", "income_limit": 200000, "state": "Assam"},
        "source_url": "https://finance.assam.gov.in",
    },
    {
        "id": "SCH_118",
        "name": "Mukhyamantri Lok Sevak Arogya Yojana (MMLSAY - Assam)",
        "issuing_body": "Medical Education & Research Department, Government of Assam",
        "state": "Assam",
        "category": "Health",
        "description": "Cashless and quick online medical bill reimbursement scheme up to ₹5,00,000 for government employees, pensioners, and eligible citizens across Assam.",
        "eligibility_rules": {"state": "Assam"},
        "source_url": "https://mmlsay.assam.gov.in",
    },
    {
        "id": "SCH_119",
        "name": "Assam Pragyan Bharati Scheme (Free College Admission & Scooty Award)",
        "issuing_body": "Higher Education Department, Government of Assam",
        "state": "Assam",
        "category": "Education & Scholarships",
        "description": "100% free admission in all government higher secondary, degree, and medical colleges for students with parental income under ₹2 Lakh, plus free scooters for top scoring girl students.",
        "eligibility_rules": {"income_limit": 200000, "state": "Assam"},
        "source_url": "https://directorateofhighereducation.assam.gov.in",
    },

    # ==========================================
    # STATE SCHEMES: DELHI NCR
    # ==========================================
    {
        "id": "SCH_120",
        "name": "Delhi Free Electricity & Water Subsidy Scheme (200 Units / 20,000 Liters)",
        "issuing_body": "Power & Delhi Jal Board, Government of NCT of Delhi",
        "state": "Delhi",
        "category": "Renewable Energy",
        "description": "100% electricity subsidy for domestic consumption up to 200 units per month, 50% subsidy up to 400 units, and free lifeline potable water up to 20,000 liters per household per month.",
        "eligibility_rules": {"state": "Delhi", "domestic_consumer": True},
        "source_url": "https://delhi.gov.in",
    },
    {
        "id": "SCH_121",
        "name": "Delhi Jai Bhim Mukhyamantri Pratibha Vikas Yojana",
        "issuing_body": "SC/ST/OBC Welfare Department, Government of NCT of Delhi",
        "state": "Delhi",
        "category": "Education & Scholarships",
        "description": "Free coaching at top empaneled private coaching institutes plus ₹2,500 monthly stipend for SC, ST, OBC, and EWS students of Delhi preparing for UPSC, SSC, Banking, JEE, NEET, and CLAT.",
        "eligibility_rules": {"income_limit": 800000, "state": "Delhi"},
        "source_url": "https://scstwelfare.delhi.gov.in",
    },
    {
        "id": "SCH_122",
        "name": "Delhi Mukhyamantri Mahila Samman Yojana (₹1,000/Month)",
        "issuing_body": "Women and Child Development, Government of NCT of Delhi",
        "state": "Delhi",
        "category": "Women & Child",
        "description": "Direct monthly financial allowance of ₹1,000 for adult women aged 18 and above who are non-taxpayers and not receiving any other government pension.",
        "eligibility_rules": {"min_age": 18, "gender": "Female", "non_taxpayer": True, "state": "Delhi"},
        "source_url": "https://wcd.delhi.gov.in",
    },
    {
        "id": "SCH_123",
        "name": "Delhi Old Age Assistance Pension Scheme",
        "issuing_body": "Department of Social Welfare, Government of NCT of Delhi",
        "state": "Delhi",
        "category": "Social Justice & Pension",
        "description": "Monthly pension assistance of ₹2,000 for senior citizens aged 60 to 69 years, and ₹2,500 for senior citizens aged 70 years and above residing in Delhi.",
        "eligibility_rules": {"min_age": 60, "income_limit": 100000, "state": "Delhi"},
        "source_url": "https://socialwelfare.delhi.gov.in",
    },

    # ==========================================
    # CENTRAL GOVERNMENT: LABOUR, MSME & MISC
    # ==========================================
    {
        "id": "SCH_124",
        "name": "Atmanirbhar Bharat Rojgar Yojana (ABRY - EPFO Subsidy)",
        "issuing_body": "Ministry of Labour and Employment",
        "state": None,
        "category": "Labour & Employment",
        "description": "Government payment of both employee (12%) and employer (12%) share of EPF contribution for 2 years for newly hired formal workers earning up to ₹15,000 per month.",
        "eligibility_rules": {"income_limit": 180000},
        "source_url": "https://www.epfindia.gov.in",
    },
    {
        "id": "SCH_125",
        "name": "Mission Karmayogi & Capacity Building Program",
        "issuing_body": "Department of Personnel and Training",
        "state": None,
        "category": "Skill Development",
        "description": "Digital learning and competency building platform for civil servants and public sector personnel across India.",
        "eligibility_rules": {},
        "source_url": "https://karmayogi.gov.in",
    },
]


def generate_schemes():
    """Writes the curated 125+ schemes to backend/app/db/schemes_seed.json."""
    current_dir = os.path.dirname(os.path.abspath(__file__))
    output_path = os.path.join(current_dir, "schemes_seed.json")
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(SCHEMES, f, indent=2, ensure_ascii=False)
    print(f"Successfully compiled {len(SCHEMES)} comprehensive Central & State welfare schemes to {output_path}")


if __name__ == "__main__":
    generate_schemes()
